/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.AccountController;
import Controller.UserController;
import java.awt.Color;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.util.HashMap;
import javax.swing.JOptionPane;
import model.User;

/**
 *
 * @author Dev khatri
 */
public class SignUp extends javax.swing.JFrame {

    /**
     * Creates new form SignUp
     */
    private HashMap<String,String> fieldsData = new HashMap<>();
    private UserController AuthController;
    private AccountController accountController;
    public SignUp() {
        this.AuthController = new UserController();
        this.accountController = new AccountController();
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        fatherNameField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Dof = new com.toedter.calendar.JDateChooser();
        emailField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        maleRadiobtn = new javax.swing.JRadioButton("Married");
        femaleRadiobtn = new javax.swing.JRadioButton();
        addressField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        phoneNumerField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        signUpBtn = new javax.swing.JButton();
        errorLabel = new javax.swing.JLabel();
        loginBtn = new javax.swing.JButton();
        cnicField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();

        buttonGroup1.add(maleRadiobtn);
        buttonGroup1.add(femaleRadiobtn);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(670, 660));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Registration Form");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, 215, 46));

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel3.setText("Name : ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 68, 25));

        nameField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nameField.setName("nameTxtField"); // NOI18N
        getContentPane().add(nameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, 461, 33));

        fatherNameField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        fatherNameField.setName("fathernameTxtField"); // NOI18N
        getContentPane().add(fatherNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, 461, 33));

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel4.setText("Date Of Birth :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, 25));

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel5.setText("Father's Name : ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, 25));

        Dof.setName("Dof"); // NOI18N
        getContentPane().add(Dof, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, 461, 32));

        emailField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        emailField.setName("emailTxtField"); // NOI18N
        getContentPane().add(emailField, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 300, 461, 33));

        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel6.setText("Email : ");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 63, 25));

        jLabel7.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel7.setText("Martial Status :");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, -1, 25));

        maleRadiobtn.setFont(new java.awt.Font("Segoe UI", 0, 14));
        maleRadiobtn.setActionCommand("Married");
        maleRadiobtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleRadiobtnActionPerformed(evt);
            }
        });
        getContentPane().add(maleRadiobtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 350, -1, -1));

        femaleRadiobtn.setFont(new java.awt.Font("Segoe UI", 0, 14));
        femaleRadiobtn.setText("Unmarried");
        femaleRadiobtn.setActionCommand("Unmarried");
        getContentPane().add(femaleRadiobtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 350, -1, -1));

        addressField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        addressField.setName("residental_Address_Txt"); // NOI18N
        getContentPane().add(addressField, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 440, 460, 33));

        jLabel8.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel8.setText("Residental Address");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 140, 25));

        phoneNumerField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        phoneNumerField.setName("cityTxtField"); // NOI18N
        phoneNumerField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                phoneNumberKeypress(evt);
            }
        });
        getContentPane().add(phoneNumerField, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 500, 458, 33));

        jLabel9.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel9.setText("Phone number :");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 500, 130, 25));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Personal Information");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, 293, 46));

        signUpBtn.setBackground(new java.awt.Color(0, 0, 0));
        signUpBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        signUpBtn.setForeground(new java.awt.Color(255, 255, 255));
        signUpBtn.setText("Sign Up");
        signUpBtn.setName("nextBtn"); // NOI18N
        signUpBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signUpBtnActionPerformed(evt);
            }
        });
        getContentPane().add(signUpBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 540, 458, 41));
        getContentPane().add(errorLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 460, -1));

        loginBtn.setBackground(new java.awt.Color(0, 0, 0));
        loginBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        loginBtn.setForeground(new java.awt.Color(255, 255, 255));
        loginBtn.setText("Login");
        loginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtnActionPerformed(evt);
            }
        });
        getContentPane().add(loginBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 590, 460, 40));

        cnicField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cnicField.setName("stateTxtField"); // NOI18N
        cnicField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cnicKeyPress(evt);
            }
        });
        getContentPane().add(cnicField, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 390, 458, 33));

        jLabel10.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel10.setText("Cnic:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 82, 25));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void maleRadiobtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleRadiobtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maleRadiobtnActionPerformed

    private void signUpBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signUpBtnActionPerformed
        // TODO add your handling code here:
        errorLabel.setForeground(Color.red);
        if(getName().length() == 0 && getFatherName().length() == 0 && getDof().length() == 0 && getemail().length() == 0 && getmartialStatus().length() == 0
               && getCnic().length() == 0 && getAddress().length() == 0&& getphonenumber().length() == 0){
            errorLabel.setText("Fields can't empty");
            return;
        }else if(getName().length() == 0){
             errorLabel.setText("Name field is empty");
             return;
        }else if(getFatherName().length() == 0){
             errorLabel.setText("Father name field is empty");
             return;
        }else if(getDof().length() == 0){
             errorLabel.setText("Date of birth is not chosen");
             return;
        }else if(getemail().length() == 0){
             errorLabel.setText("Email field is empty");
             return;
        }else if(getmartialStatus().length() == 0){
             errorLabel.setText("MartialStatus is not chosen");
             return;
        }else if(getCnic().length() == 0){
             errorLabel.setText("Cnic field is empty");
             return;
        
        }else if (getCnic().length() < 11){
            errorLabel.setText("Cnic number should be of 13 digits");
            return;
        }
        else if(getAddress().length() == 0){
             errorLabel.setText("Address field is empty");
             return;
        }else if(getAddress().length() > 70){
             errorLabel.setText("Address field length should of 70");
             return;
        }
        else if(getphonenumber().length() == 0){
             errorLabel.setText("phone number field is empty");
             return;
        }else if(getphonenumber().length() < 11){
            errorLabel.setText("phone number should be of 11 digits");
            return;
        }
         errorLabel.setText("");
         registerUser();
    }//GEN-LAST:event_signUpBtnActionPerformed

    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new LoginPage().setVisible(true);
    }//GEN-LAST:event_loginBtnActionPerformed

    private void cnicKeyPress(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cnicKeyPress
        // TODO add your handling code here:
         if(evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9' ||  evt.getKeyCode() == KeyEvent.VK_BACK_SPACE){
             if(cnicField.getText().length() >= 11 && evt.getKeyCode() != KeyEvent.VK_BACK_SPACE){
                 cnicField.setEditable(false);
                 return;
             }
             cnicField.setEditable(true);
         }
        else cnicField.setEditable(false);
    }//GEN-LAST:event_cnicKeyPress

    private void phoneNumberKeypress(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_phoneNumberKeypress
        // TODO add your handling code here:
          if(evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9' ||  evt.getKeyCode() == KeyEvent.VK_BACK_SPACE){
              if(phoneNumerField.getText().length() >= 11 && evt.getKeyCode() != KeyEvent.VK_BACK_SPACE){
                  phoneNumerField.setEditable(false);
                  return;
              }
              phoneNumerField.setEditable(true);
          }
          else phoneNumerField.setEditable(false);
    }//GEN-LAST:event_phoneNumberKeypress
  public void setNextListner(ActionListener listener){
      signUpBtn.addActionListener(listener);
  }
  public String getName(){
      return nameField.getText();
  }
  public String getFatherName(){
      return fatherNameField.getText();
  }
  public String getDof(){
      if(Dof.getDate() == null) return "";
      return Dof.getDate().toString();
  }
  public String getemail(){
      return emailField.getText();
  }
  public String getmartialStatus(){
      if(buttonGroup1.getSelection() == null) return "";
      return  buttonGroup1.getSelection().getActionCommand();
  }
  public String getAddress(){
      return addressField.getText();
  }
  public String getphonenumber(){
      return phoneNumerField.getText();
  }
  public String getCnic(){
      return cnicField.getText();
  }
  private void registerUser(){
      User User = AuthController.registerUser(getName(), getFatherName(), getDof(), getemail(), getmartialStatus(), getCnic(), getAddress(), getphonenumber());
      if(User != null){
      accountController.createAccount(User,this);
      }
    //  AuthController.createAccountIdColumn(userId, accountId,this);
  }
    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser Dof;
    private javax.swing.JTextField addressField;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField cnicField;
    private javax.swing.JTextField emailField;
    public javax.swing.JLabel errorLabel;
    private javax.swing.JTextField fatherNameField;
    private javax.swing.JRadioButton femaleRadiobtn;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton loginBtn;
    private javax.swing.JRadioButton maleRadiobtn;
    private javax.swing.JTextField nameField;
    private javax.swing.JTextField phoneNumerField;
    private javax.swing.JButton signUpBtn;
    // End of variables declaration//GEN-END:variables
}
